baseURL = "http://izmalkov.net/"
languageCode = "en"
title = "Vladimir Izmalkov"
theme = "initio"

[params]
    name = "Vladimir Izmalkov"
    description = "Documentation engineer"
    email = "admin@izmalk.ru"
    phone = "+7 903 225 22 11"
    address = "Moscow, Russia"
    year = 2022
    avatar = "images/guy.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head.jpg"
    favicon = "images/favicon.ico"
    DateForm = "August 2, 2022"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

# [params.disqus]
#     site = "hugo-initio-site.disqus.com"

# [params.sharethis]
#     property = "123456789012345678901234"
#     custom = true

[params.google.analytics]
    trackerID = "G-03S8GTWJM8"

# [[params.social]]
# 	title = "facebook"
# 	url = "https://www.facebook.com/nickname"
#     icon = "fab fa-facebook-square"
#     footer = true
#     sharethis = true
#     network = "facebook"
# [[params.social]]
# 	title = "twitter"
# 	url = "https://twitter.com/nickname"
#     icon = "fab fa-twitter-square"
#     footer = true
#     sharethis = true
#     network = "twitter"
# [[params.social]]
# 	title = "instagram"
# 	url = "https://www.instagram.com/nickname"
#     icon = "fab fa-instagram"
#     footer = true
#     sharethis = false
#     network = ""
# [[params.social]]
# 	title = "google+"
# 	url = "https://plus.google.com/+nickname"
#     icon = "fab fa-google-plus-square"
#     footer = false
#     sharethis = true
#     network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/vaizmalkov"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
 # [[params.social]]
	# title = "tumblr"
	# url = "https://nickname.tumblr.com"
 #    icon = "fab fa-tumblr-square"
 #    footer = false
 #    sharethis = false
 #    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/izmalk"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:admin@izmalk.ru"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
