baseURL = "https://izmalk.com/"
languageCode = "en"
title = "Vladimir Izmalkov"
theme = "initio"

[params]
    name = "Vladimir Izmalkov"
    description = "Documentation engineer"
    email = "job@izmalk.uk"
    phone = "+44 77 602 40 604"
    address = "London, United Kingdom"
    year = 2023
    avatar = "images/guy.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/background.jpg"
    favicon = "images/favicon.ico"
    DateForm = "October 2, 2023"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "summary"
    url = "/post/summary"
    weight = 2
[[menu.main]]
    name = "education"
    url = "/post/education"
    weight = 3
[[menu.main]]
    name = "work experience"
    url = "/post/exp"
    weight = 4
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

# [params.disqus]
#     site = "hugo-initio-site.disqus.com"

# [params.sharethis]
#     property = "123456789012345678901234"
#     custom = true

[params.google.analytics]
    trackerID = "G-03S8GTWJM8"

# [[params.social]]
# 	title = "facebook"
# 	url = "https://www.facebook.com/nickname"
#     icon = "fab fa-facebook-square"
#     footer = true
#     sharethis = true
#     network = "facebook"
# [[params.social]]
# 	title = "twitter"
# 	url = "https://twitter.com/nickname"
#     icon = "fab fa-twitter-square"
#     footer = true
#     sharethis = true
#     network = "twitter"
# [[params.social]]
# 	title = "instagram"
# 	url = "https://www.instagram.com/nickname"
#     icon = "fab fa-instagram"
#     footer = true
#     sharethis = false
#     network = ""
# [[params.social]]
# 	title = "google+"
# 	url = "https://plus.google.com/+nickname"
#     icon = "fab fa-google-plus-square"
#     footer = false
#     sharethis = true
#     network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/vaizmalkov"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "telegram"
	url = "https://t.me/BoBacTbli"
    icon = "fab fa-telegram-plane"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "github"
	url = "https://github.com/izmalk"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:job@izmalk.uk"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
